### ISSUE TITLE
O modelo de ID atual pode gerar duplicatas entre decks diferentes.

### ISSUE THREAD

**Issue by PedroBicudo** [PedroBicudo/MediaToAnki#6]
### Problema
O projeto gera IDs baseado no tempo em que a cena acontece, logo, se houver uma nova cena em outro deck com o mesmo tempo, a cena original vai ser sobrescrita.

#### Exemplo
Subtitle A
```
00:05:00.000 --> 00:08:00.000
Uma frase pertencente a subtitle A.
```
Essa subtitle vai gerar dois arquivos (mp3 e png), nomeados 300_480.mp3 e 300_480.png.

Subtitle B
```
00:05:00.000 --> 00:08:00.000
Uma frase pertencente a subtitle B.
```
Essa subtitle também vai gerar dois arquivos nomeados 300_480.mp3 e 300_480.png.

## TODO
- [x] Novo modelo de identificação de media: `datetime_id` + `scene_id`.
     - [x] Criar uma váriavel responsável por armazenar a identificação da cena (`scene_id`).
     - [x] Criar uma variável que armazena a data de criação da anotação (`datetime_id`).

Comportamento esperado
```
scene_id = 300400
datettime_id = 12122021

# subtitle_id = f"{datetime_id}{scene_id}"
subtitle_id = "12122021300400"
```
